### PR TITLE
Add tool to retrieve history data from Tesla cloud

### PR DESCRIPTION
**Pull request by mcbirse**
Add tool to retrieve history data from Tesla cloud as per #12 

@jasonacox - Usage instructions added to the tools README, however just thinking may want to consider moving each tools instructions to their own README perhaps? Then the main README could simply be a summary/description of available tools, with links to the specific tool. Please feel free to modify/change as required if you think this would be a good idea.

### CODE REVIEW

**Comment by jasonacox** [comment]
Great work @mcbirse !!!  Thank you! This is a great addition to the project.  I agree with you on the separation of the tools.  I'll work on that.

**Comment by jasonacox** [comment]
Hi @mcbirse - I moved the tools into their own folders with an index list in the [/tools](https://github.com/jasonacox/Powerwall-Dashboard/tree/main/tools) folder.  Take a look and let me know if this makes sense or if we should adjust.

**Comment by mcbirse** [comment]
Hi @jasonacox - Looks great and makes sense! I think this should be much more manageable going forward if the list of tools continues to expand.

**Comment by jgleigh** [comment]
I did have to move the .conf and .auth files into the new folder so the script could find them again.

**Comment by jasonacox** [comment]
Ah!  That's a great point @jgleigh  - For anyone who set it up prior to me moving the tools, you will need to move your setup files into the new folder (or run the `python3 tesla-history.py --login` again).

**Pull request merged**
