### PR TITLE
Fix month tags tool - revisions for untagged data

### PR DESCRIPTION
**Pull request by mcbirse**
Some "safety" revisions for this tool:
* Data points without any month tags will now have the month/year tag added (I realised untagged data could be deleted otherwise)
* Specifically check data type of each value and replicate this in line protocol format correctly (just in case there are int, string, or bool type values. Should not happen since all current values are floats, but you never know...)

### CODE REVIEW

**Comment by cwagz** [comment]
@mcbirse - Thank you for making this tool. The tool identified all my data before the fix as needing correction and ran without issue. Unfortunately, all data was deleted from 2/27/22 @ 16:12 to 3/6/22 @ 15:41. Let me know if there is any way I can help figure out what happened. I pulled the tool down after this merge. I have a backup from last night if that would help.

I assume I can rebuild the data for these days using the script to pull it from the cloud.

image

image

**Comment by mcbirse** [comment]
@cwagz - Oh no!! I'm not sure why this has happened.

Just confirming it corrected the other data okay, but for some reason just these few days were deleted?

I think I need to analyse your data - is there any way I can get a copy of your backup please? Share file link e-mailed to me directly perhaps (michael@birse.com.au).

This issue concerns me and I wouldn't want it to happen for people using the tool. You could use the history import tool to restore that, however this will not restore other data if there was any (i.e. vitals, strings, pwtemps, etc.), the only option for those is to restore from backup. 😞 

@jasonacox Just wondering if you have any feedback and/or could test the tool (on a test system) - any issues?

**Comment by cwagz** [comment]
@mcbirse - I believe all the other data was corrected. I am honestly not sure how to tell 100% though. I just noticed the gap in my yearly data and when I pull up those days the data is all missing.

I have emailed OneDrive links with yesterday's backup and a backup I just ran.

**Comment by mcbirse** [comment]
Thanks @cwagz - I will investigate and let you know what I find.

> I believe all the other data was corrected. I am honestly not sure how to tell 100% though.

You could run the Tesla history import tool in --test mode for your entire date range from install to now, and see if any other data gaps are identified.

**Comment by cwagz** [comment]
@mcbirse was able to help me get my data resolved. Nothing had been deleted. Steps to fix:

- completely restart the dashboard (I just rebooted my virtual machine)
- run python3 fixmonthtags.py --rebuild (say no to correcting month tags)
- Check dashboard - Data was all showing again after these steps
- run python3 fixmonthtags.py again to fix any remaining month tag issues

After this I have no more month tag issues and all the data is displaying again.

**Pull request merged**
