### PR TITLE
add .gitattributes file

### PR DESCRIPTION
**Pull request by YesThatAllen**
Prevents issues such as .sh files being borked on windows OS (ref https://github.com/jasonacox/Powerwall-Dashboard/issues/155#issuecomment-1381300040 )

### CODE REVIEW

**Comment by YesThatAllen** [comment]
This is related to #265 but I'm putting it in a separate branch because merging this may cause some issues on various users' locals.

It's like ripping off a band-aid though.. better to address any pain & get it over with.

**Comment by jasonacox** [comment]
> this may cause some issues on various users' locals.

What would be the expected scenario where that occurs?  A vast majority of our community just use `setup.sh` and `upgrade.sh` with no customization.  I tend to optimize and accommodate those to ensure no impact for upgrades. This seems sane/safe, just asking for edge cases that might impact the majority.

Thanks for your expertise! 🙏  I had no idea about these files and intend to explore them for my other projects. 😉

**Comment by YesThatAllen** [comment]
Yea, sorry to have gone all doom & gloom here 😱, it shouldn't be a big deal.

The `.gitattributes` file is mostly focused on unifying line endings:
 - linux's `lf`
vs 
 - windows's `crlf` 

linux basically sees `crlf`  as two line endings, and `bash` just can't cope (that's the weirdness you saw in #265 )
So, this helps with all that.

The worst issues I've seen relate to image files & files with unicode names.
If the repo had image or other binary files, we'd need to make sure their line endings were binary.. eg `*.png  binary` so that git would know to leave the line endings alone.

What I don't know is if people will see issues with `git stash` & `git pull --rebase` when trying to retain changes.

Worst case scenario: a .sh file was edited locally on a windows computer, and had `crlf` line endings.. and now the script is going to force it to `lf` line endings.

Should be easy enough to test on a windows box, I just don't have a good test bed (with docker on windows, etc) handy. AND I also don't think you suggest edits to files which are in the repo (untracked files shouldn't be affected.


I guess the biggest issue is hitting a problem mid-upgrade script. What would happen if the script failed here [upgrade.sh#L84-L90](https://github.com/jasonacox/Powerwall-Dashboard/blob/0f150c780dae323b27d94bcd8b9f0f30f8315ae1/upgrade.sh#L84-L90) ?

**Comment by YesThatAllen** [comment]
I just used `git add --renormalize .` on the repo, to see what other issues might come up. Two out of six `.flux` files had been committed as `crlf` to I ~fixed~ unified those.

And, for the record.. there's no need to add every kind of extension.. that first line says "git, you can pretty well assume files are plain text, and you can set line endings according to the current OS default." I'm doing it more for clarify.

**Comment by jasonacox** [comment]
Thanks again @YesThatAllen !  I merged and tagged this as v2.9.6.

**Pull request merged**
