### PR TITLE
Powerwall Temps support

### PR DESCRIPTION
**Pull request by jasonacox**
## v4.6.0 - Powerwall Temps

* Updates to pypowerwall proxy v0.12.0 t66 (https://github.com/jasonacox/pypowerwall/pull/114) which supports a new TEDAPI call to gather vitals that includes Powerwall Temps.
* Updates `telegraf.conf` to read Dashboard VERSION using `ver.sh`.
* Updates `dashboard.json` to include Powerwall Temps and current Dashboard Version.
* Add support for pypowerwall environmental variable `PW_NEG_SOLAR` to allow users to zero out negative values (see `pypowerwall.env.xample`)

image

Credit to @ygelfand (and [go-powerwall proxy](https://github.com/ygelfand/go-powerwall)) for discovery and reported in https://github.com/jasonacox/Powerwall-Dashboard/discussions/392#discussioncomment-11360474

### CODE REVIEW

**Comment by mcbirse** [comment]
Hooray, this is brilliant Jason, great to see we will finally get temps back - was hoping we would one day! Thanks @ygelfand for the fantastic discovery work, well done!

The Dashboard Version is a nice addition too, love it.

**Comment by jasonacox** [comment]
Thanks @mcbirse !  What firmware version are you running? I'm on 24.36.2 and would like confirmation that it also works on older firmwares (though I'm fairly confident it should).

I merged the changes.

**Comment by chrisgonyea** [comment]
Question, I upgraded to 4.6.0 but my Powerwall temps graph is empty.  I have two PW2s (firmware 24.36.2) and using Powerwall-Dashboard in local mode. It's the only graph not showing data. Any ideas?

Screenshot 2024-11-30 at 11 34 56 AM

**Comment by jasonacox** [comment]
Hi @chrisgonyea - You will need to be using TEDAPI hybrid or full mode and not just local mode.  Please run `verify.sh` and to see which mode you are using. The temp data is only available in the TEDAPI payload. Here is an example:

image

Hi @martinmanyhats - Interesting. Can you run `verify.sh`? I didn't think the PW3 would work without TEDAPI "full" mode, but perhaps this new firmware adds the local gateway portal to the PW3?  If you don't get any information in verify.sh, could you paste the logs from pypowerwall (first part): `docker logs pypowerwall`.

**Comment by farberm** [comment]
I have the same issue.. no temps... and verify.sh reports TEDPAI as full mode ....?
FW 24.36.1 Dashboard 4.6.0
Screenshot 2024-11-30 at 7 53 28 PM

**Comment by martinmanyhats** [comment]
Output from verify.sh:

$ ./verify.sh
Verify Powerwall-Dashboard 4.6.0 on Linux - Timezone: Europe/London
----------------------------------------------------------------------------
This script will attempt to verify all the services needed to run
Powerwall-Dashboard. Use this output when you open an issue for help:
https://github.com/jasonacox/Powerwall-Dashboard/issues/new


Checking pypowerwall
----------------------------------------------------------------------------
 - Config File pypowerwall.env: GOOD
 - Container (pypowerwall): GOOD
 - Service (port 8675): GOOD
 - Version: 0.12.0 Proxy t66
 - Powerwall State: CONNECTED - Firmware: 24.28.2-zest-6
 - Site Name: My Home
 - Gateway TEDAPI: Available (192.168.91.1)
 - TEDAPI Vitals: Connected - Mode: full
 - Cloud Mode: NO

Checking telegraf
----------------------------------------------------------------------------
 - Config File telegraf.conf: GOOD
 - Local Config File telegraf.local: GOOD
 - Container (telegraf): GOOD
 - Version: Telegraf 1.28.2 (git: HEAD@8d9cf395)

Checking influxdb
----------------------------------------------------------------------------
 - Config File influxdb.conf: GOOD
 - Environment File influxdb.env: GOOD
 - Container (influxdb): GOOD
 - Service (port 8086): GOOD
 - Filesystem (./influxdb): GOOD
 - Version: InfluxDB shell version: 1.8.10

Checking grafana
----------------------------------------------------------------------------
 - Config File grafana.env: GOOD
 - Container (grafana): GOOD
 - Service (port 9000): GOOD
 - Filesystem (./grafana): GOOD
 - Version: Grafana CLI version 9.1.2

Checking weather411
----------------------------------------------------------------------------
 - Container (weather411): GOOD
 - Service (port 8676): GOOD
 - Weather: {"temperature": 13.59}
 - Version: 0.2.3

All tests succeeded.

**Comment by chrisgonyea** [comment]
> Hi @chrisgonyea - You will need to be using TEDAPI hybrid or full mode and not just local mode. Please run `verify.sh` and to see which mode you are using. The temp data is only available in the TEDAPI payload. Here is an example:
> 
> image
> EDIT: To set up TEDPAI access, you need to enable extended vitals and re-run `setup.sh`1, see: https://github.com/jasonacox/Powerwall-Dashboard?tab=readme-ov-file#extended-device-vitals-metrics-beta

Interesting, somehow I had an old login that was only getting some data but not all. Already had the route configured via a static route on my Unifi router. Figured out the correct login and we're good now in hybrid mode, thanks @jasonacox! 👍

```
Checking pypowerwall
----------------------------------------------------------------------------
 - Config File pypowerwall.env: GOOD
 - Container (pypowerwall): GOOD
 - Service (port 8675): GOOD
 - Version: 0.12.0 Proxy t66
 - Powerwall State: CONNECTED - Firmware: 24.36.2
 - Site Name: My Home
 - Gateway TEDAPI: Available (192.168.91.1)
 - TEDAPI Vitals: Connected - Mode: hybrid
 - Cloud Mode: NO
```

**Comment by farberm** [comment]
I do not know if this will help however....

....I can see many of the vitals by going to http://localhost:8675/vitals but when I go to http://localhost:8675/temps .....all I get is {}

This is the log from pypowerwall...

12/01/2024 04:10:23 PM [proxy] [INFO] pyPowerwall [0.12.0] Proxy Server [t66] - HTTP Port 8675
12/01/2024 04:10:23 PM [proxy] [INFO] pyPowerwall Proxy Started
12/01/2024 04:10:24 PM [proxy] [INFO] pyPowerwall Proxy Server - Local Mode
12/01/2024 04:10:24 PM [proxy] [INFO] Connected to Energy Gateway 192.168.91.1 (Home)
12/01/2024 04:10:24 PM [proxy] [INFO] TEDAPI Mode Enabled for Device Vitals (full)
12/01/2024 04:11:08 PM [pypowerwall.tedapi.pypowerwall_tedapi] [WARNING] This API [get_api_auth_toggle_supported] is using mock data in tedapi mode. This message will be printed only once at the warning level.
12/01/2024 04:11:08 PM [pypowerwall.tedapi.pypowerwall_tedapi] [WARNING] This API [get_api_system_status_grid_faults] is using mock data in tedapi mode. This message will be printed only once at the warning level.
12/01/2024 04:11:08 PM [pypowerwall.tedapi.pypowerwall_tedapi] [WARNING] This API [get_api_unimplemented_timeout] is using mock data in tedapi mode. This message will be printed only once at the warning level.
12/01/2024 04:11:08 PM [pypowerwall.tedapi.pypowerwall_tedapi] [WARNING] This API [get_api_sitemaster] is using mock data in tedapi mode. This message will be printed only once at the warning level.
12/01/2024 04:11:08 PM [pypowerwall.tedapi.pypowerwall_tedapi] [WARNING] This API [get_api_powerwalls] is using mock data in tedapi mode. This message will be printed only once at the warning level.

**Comment by jasonacox** [comment]
Sadly, it may be that the Powerwall 3 does not have temps in the payload. I created a new issue to track: https://github.com/jasonacox/Powerwall-Dashboard/issues/550

The temp data could be located in a different spot or require a different query for Powerwall 3 systems.

**Comment by mcbirse** [comment]
> Thanks @mcbirse ! What firmware version are you running? I'm on 24.36.2 and would like confirmation that it also works on older firmwares (though I'm fairly confident it should).

@jasonacox - sorry for my delayed response. Unfortunately I'm also on 24.36.2 now so can't confirm if this works on an older version firmware.

Can confirm it works on 24.36.2 though! 😄 

image

Interesting my temp graph looks a bit different to yours.... quick changes in temp (could be fans kicking in?) rather than gradual changes.

I checked back on old data and it was always like this, so the data we are getting is good and consistent with my previous recorded temps for my PW2.

**Comment by youzer-name** [comment]
Just to answer a question no one was asking... yes, if you stack 3 Powerwalls, the one in the middle stays warmer.

I added the mean temp to the graph. It's been about 1° C warmer on average over the past few days.

image

My graph also looks like Jason's without the sudden ups and downs.

**Comment by BJReplay** [comment]
> Just to answer a question no one was asking... yes, if you stack 3 Powerwalls, the one in the middle stays warmer.


I misread that for a moment and thought _"has @youzer-name upgraded to three **Powerwall 3**s?"_ and thought that was the ultimate in chasing upgrades, but, no, you have just upgraded your monitoring!

**Comment by youzer-name** [comment]
Lol, I should have specified that it's 3x Powerwall 2's.  I started with 2 PW 2's but added the third when they were running a sale a while back.

**Comment by jasonacox** [comment]
> quick changes in temp (could be fans kicking in?)

@mcbirse I think this is a temperature thing (southern vs norther hemisphere) and possibly also when combined with heavy load use (e.g. A/C on battery).  We are in the winter now with 10-20 degree days and no fan or A/C running. I looked back a few years when we had the old vitals and saw the smooth curves then too, but jagged curves like your during the summer (when we were at 25-40 degree days). 

image

**Comment by mcbirse** [comment]
Hi Jason, oh yes you're right - definitely temperature and load related. I just checked back to a cold day in winter last year...

image

**Comment by wiltocking** [comment]
We have a Powerwall+ with a hardwired Gateway (no wifi) to the local network set with a fixed IP. While I thought I had local access to the Tesla API it seems I do not because this latest update shows No Data in PW Temps. Ran verify.sh and it showed TEDAPI as "Not Available", however when running setup.sh it showed the correct current credentials of the Gateway fixed IP and password. Got a bit further by running add_route.sh and typing the fixed IP again, verify.sh now shows the following:

image

I've rerun setup.sh a couple of times and nothing changes. What's missing to get Vitals Connected / Mode Full? Any help is appreciated.

**Comment by DMBlakeley** [comment]
I had a similar situation until I added a static routing path to my router configuration which opened up the 192.168.91.xxx range. I have a Linksys MX8500 router.

**Comment by wiltocking** [comment]
> I had a similar situation until I added a static routing path to my router configuration which opened up the 192.168.91.xxx range. I have a Linksys MX8500 router.

I can access the old Gateway Config page from the browser with the static IP and it responds to pings. Everything is in the same subnet so not sure if that's the issue.

**Comment by DMBlakeley** [comment]
Did you have your password entries correct?

I had an old version of the `pypowerwall.env` file. Picked up the new sample version of this file. You need to use your account password for the `PW_PASSWORD` entry and the password on the Powerwall label for the `PW_GW_PWD` entry.

**Comment by wiltocking** [comment]
> Did you have your password entries correct?
> 
> I had an old version of the `pypowerwall.env` file. Picked up the new sample version of this file. You need to use your account password for the `PW_PASSWORD` entry and the password on the Powerwall label for the `PW_GW_PWD` entry.

Interesting, seems the file is outdated and doesn't have the PW_GW_PWD entry at all. I've downloaded the latest too and just to confirm PW_PASSWORD is supposed to be the Tesla Account or the Gateway sticker password again?

**Comment by DMBlakeley** [comment]
PW_PASSWORD is the Tesla Account password.

**Comment by DMBlakeley** [comment]
Looping back to my first comment. Your home network is on 192.128.1.xxx. The Gateway is on the 192.168.91.xxx network. These are separate networks.

Took me a while to realize that I needed to configure a static from my home network to the Gateway network. Not sure what router you have but if you search for "static route configuration" you will most likely find some instructions.

Once the network is establish, then the new pypowerwall.env is the correct format with your Tesla account password for the PW_PASSWORD entry and the password on the Powerwall label for the PW_GW_PWD entry.

**Comment by wiltocking** [comment]
> Looping back to my first comment. Your home network is on 192.128.1.xxx. The Gateway is on the 192.168.91.xxx network. These are separate networks.
> 
> Took me a while to realize that I needed to configure a static from my home network to the Gateway network. Not sure what router you have but if you search for "static route configuration" you will most likely find some instructions.
> 
> Once the network is establish, then the new pypowerwall.env is the correct format with your Tesla account password for the PW_PASSWORD entry and the password on the Powerwall label for the PW_GW_PWD entry.

So software bug maybe? Using the Tesla One App, the Gateway has the static IP set to 192.168.1.xxx and it responds to pings at that IP and it's accessible via the browser there too... the 192.168.91.xxx device doesn't exists in my configuration and that's why the Dashboard is struggling maybe?

**Comment by DMBlakeley** [comment]
On your first post, the screen grab showed that the "Gateway TEDAPI: Available 192.168.91.1"

You are correct, that 192.168.91.1 does not exist on your 192.168.1.1 network. For it to exist, you need to configure your router for access to this parallel network. What router are you using?

**Comment by wiltocking** [comment]
Correct me if I'm wrong, the 192.168.91.1 device only exists when connected to the native Gateway TEG-xxx Wi-Fi right? My configuration is all wired, why would the ethernet connection to the Gateway (with it's own MAC and router assigned Static IP) need that device to exist?

**Comment by jasonacox** [comment]
Hi @wiltocking - you were close to having it work when verify.sh was showing that it could connect to 192.168.91.1. You just needed to manually add the `PW_GW_PWD` entry to pypowerwall.env and restart pypowerwall with `./compose-dash.sh up -d`.

Alternatively, you could do this:

Run `add_route.sh` to add the route to the TEDAPI interface.
Run `setup.sh` and update credentials: 

```
$ ./setup.sh 
Powerwall Dashboard (v4.6.0) - SETUP
-----------------------------------------
Select configuration mode:

Current: None

 1 - Local Access   (Powerwall 1, 2, or + using the Tesla Gateway on LAN) - Default
 2 - Tesla Cloud    (Solar-only systems or Powerwalls without LAN access)
 3 - FleetAPI Cloud (Powerwall systems using Official Telsa API)
 4 - Powerwall 3    (Powerwall 3 using the local Tesla Gateway)

Select mode: 1

Timezone (leave blank for America/Los_Angeles)
Enter Timezone: 

Current Credentials:

PW_EMAIL=myemail@myaddress.com
PW_PASSWORD=myTeslaPassword
PW_HOST=192.168.91.1
PW_TIMEZONE=America/Los_Angeles
TZ=America/Los_Angeles
PW_DEBUG=no
PW_STYLE=grafana-dark
PW_GW_PWD=XXXXXXXXX

Update these credentials? [y/N] Y

Enter credentials for Powerwall...
Password: myTeslaPassword
Email: myemail@myaddress.com
Found Powerwall Gateway at 192.168.91.1
Use this IP? [Y/n] Y

Congratulations!
Extended Device Metrics (vitals) are available on this endpoint via TEDAPI.
However, you will need the Gateway password to access them.
This password is often on the QR code on the Powerwall Gateway unit.

Enter Gateway Password or leave blank to disable: XXXXXXXXX

Do you have a Powerwall 3? [y/N] N
```

As to the routing question. The 192.168.91.1 endpoint is only available on the WiFi access point or if you create a route from your LAN. For example, if you local network is 192.168.0.1/24, when you hardware your Powerwall gateway, it will be assigned an address in that network (e.g. 192.16.0.123) and you would use that as the gateway to get to 192.168.91.1, hence the `add_route.sh` script.

**Comment by wiltocking** [comment]
Morning @jasonacox thanks for the thorough reply, followed both suggestions above but TEDAPI Vitals still shows "Not Connected". 

I've attempted multiple options to get it to work, using the local IP or using the gateway IP in <code>pypowerwall.env</code> which really stumps me because the Dashboard continues to work no issues, changing <code>PW_PASSWORD=myTeslaPassword</code> to the Gateway Password, recreating the Grafana Dashboard, but no success. Everything seems to always work fine and shows the correct data except for Powerwall Temps. 

image

Thinking about cloning the repo again and redoing <code>setup.sh</code> as the next step.

**Comment by jasonacox** [comment]
> using the local IP or using the gateway IP in pypowerwall.env 

Just a note here in case it wasn't clear, for TEDAPI to work, you must use 192.168.91.1. No other IP will work (the Gateway enforces that).

> changing PW_PASSWORD=myTeslaPassword to the Gateway Password

You definitely don't want to do that!  It will continue to work for a while since you likely have a cached auth key with the right password, but when it renews it will fail and stop pulling any date. Only use the gateway password for `PW_GW_PWD`. The `PW_PASSWORD` should continue to be the password you use to log in to the Gateway directly (via web browser at the IP address of the gateway).

> Thinking about cloning the repo again and redoing setup.sh as the next step.

Good plan.  

Also, if you want to test with a command line:

```bash
# Run a test against TEDAPI endpoint

pip install pypowerwall # pull down python library

python3 -m pypowerwall.tedapi

```

**Comment by DMBlakeley** [comment]
Glad you worked it out and are now operational.

**Comment by wiltocking** [comment]
> Glad you worked it out and are now operational.

Yes, very happy that we've recovered all the lost functionality from the 23.44.3 FW updated. Wife doesn't appreciate the beauty of having a mounted iPad showing Powerwall Dashboard, but to me it's better than Christmas decorations! Thank you @DMBlakeley and @jasonacox for the support and also working on this great project for everyone's benefit.

**Comment by jasonacox** [comment]
Great job!

> Tesla only tells you to use the last five digits for everything 

I wonder if I should add a note to the setup script/instructions to ensure everyone uses the full Gateway PW. Would that have helped?

> better than Christmas decorations

Haha!  That's great @wiltocking !  😆 

Merry Christmas and Happy holidays everyone! 🎅 

image

**Pull request merged**
