### PR TITLE
v4.3.0

### PR DESCRIPTION
**Pull request by jasonacox**
Updates:

* Upgrade to pyPowerwall proxy v0.8.1 - Major refactoring of code in https://github.com/jasonacox/pypowerwall/pull/77 and https://github.com/jasonacox/pypowerwall/pull/78 and addition of new Alerts.
* Disable `GF_PATHS_PROVISIONING` from `grafana.env` base to speed up Grafana startup by @BuongiornoTexas in #461

### CODE REVIEW

**Comment by jasonacox** [comment]
To test new pypowerwall, edit `powerwall.yml` and update the pypowerwall image to:

```
jasonacox/pypowerwall:0.8.1t52
```

Restart and watch logs...

```bash
./compose-dash.sh up -d ; docker logs grafana -f
```

**Comment by jgleigh** [comment]
Not sure if you meant to suppress this in 0.8.1 or not.

[ERROR] 404 Powerwall API not found at https://192.168.1.6/api/customer/registration

**Comment by jgleigh** [comment]
Seeing this occasionally too.

[ERROR] Server-side problem at Powerwall API (status code 503) at https://192.168.1.6/api/solar_powerwall

**Comment by jasonacox** [comment]
Interesting that we see error code 503.

> The HTTP status code 503 means that the server is currently unable to handle the incoming requests. Usually, this error occurs because the server is too busy or is temporarily down for maintenance. The backend server is overloaded or beyond its capacity and cannot handle any new incoming client requests.

You wouldn't be able to hit the URL directly from a browser because you are missing the token data in the request header. To test it, you would have to use the proxy via: http://powerwall:8675/api/solar_powerwall (replace powerwall with IP address of your Powerwall).

It would be interesting to see if you are seeing errors tick up: http://powerwall:8675/stats 

I'm thinking about treating 503 similar to 429 (rate limit) to cause a cool down timer for that API call.

**Comment by jasonacox** [comment]
Testing `jasonacox/pypowerwall:0.8.2t53-beta`

**Comment by jasonacox** [comment]
Thanks for your help @jgleigh !

**Comment by jgleigh** [comment]
0.8.1
2024-04-12 17:31:05 04/12/2024 05:31:05 PM [proxy] [ERROR] Socket broken sending API response to client [doGET]: [Errno 32] Broken pipe
2024-04-12 17:31:05 04/12/2024 05:31:05 PM [proxy] [ERROR] Socket broken sending API response to client [doGET]: [Errno 32] Broken pipe
2024-04-12 17:31:09 04/12/2024 05:31:09 PM [proxy] [ERROR] Socket broken sending API response to client [doGET]: [Errno 32] Broken pipe
2024-04-12 17:31:09 04/12/2024 05:31:09 PM [proxy] [ERROR] Socket broken sending API response to client [doGET]: [Errno 32] Broken pipe
2024-04-12 17:31:09 04/12/2024 05:31:09 PM [proxy] [ERROR] Socket broken sending API response to client [doGET]: [Errno 32] Broken pipe
2024-04-12 17:31:09 04/12/2024 05:31:09 PM [proxy] [ERROR] Socket broken sending API response to client [doGET]: [Errno 32] Broken pipe

Restarted it earlier so don't have the token errors.

Will start testing 0.8.2 now.

**Comment by youzer-name** [comment]
I got this message when doing the upgrade to 4.3.0:

WARN[0000] /home/..../Powerwall-Dashboard/powerwall.extend.yml: `version` is obsolete 

That file starts with: version: "3.5"

I use the extend file to run tesla-history alongside PWD and use that to pull my Tesla solar / PPA data. Do I need to update the extend file? I noticed that the powerwall.yml doesn't have a 'version' statement.

**Comment by jasonacox** [comment]
hi @youzer-name  - This isn't causing problems other than the warning from docker compose?

You should be able to remove that version line. It shouldn't be needed with latest docker versions.

**Comment by mcbirse** [comment]
Hi @youzer-name - I also have a `powerwall.extend.yml` file with a custom docker container. 

Confirming you can simply remove the `version: "3.5"` line, which is what I did. This will fix the warning without affecting your custom docker container service definitions.

**Comment by youzer-name** [comment]
@mcbirse  Thanks for confirming.

**Pull request merged**
